### ISSUE TITLE
Store front

### ISSUE THREAD

**Issue by Kerosz** [chingu-voyages/v34-bears-team-10#23]
**__Feature Description__**
The First (Landing) Page of the E-Commerce Site

**__Major User Stories/tasks__**
- [ ] Featured Seller(s) at Store Front
- [ ] Featured Product(s) at Store Front
- [ ] Trending (or popular) Product(s) at Store Front
- [ ] Latest Product(s) at Store Front

**__Additional Considerations__**
